app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// Route::get('/', function () {
//     return view('welcome');
// });
 

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::get('socket', 'SocketController@index');
// Route::post('sendmessage', 'SocketController@sendMessage');
// Route::get('writemessage', 'SocketController@writemessage');
Route::group(['prefix' => 'admin','middleware' => ['web']], function () {
	 
 
    Route::get('register',['as' => 'register', 'uses' => 'Admin\AdminController@getRegister']);
    Route::post('register','Admin\AdminController@postRegister');
    Route::get('login',['as' => 'login', 'uses' => 'Admin\AdminController@getLogin']);
    Route::post('login','Admin\AdminController@postSignin');
    Route::get('logout',['as' => 'logout', 'uses' => 'Admin\AdminController@getLogout']);

    Route::get('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@getForgotpassword']);
    Route::post('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@postForgotpassword']);

    Route::get('forgot-password-confirm',['as' => 'forgot-password-confirm', 'uses' => 'Admin\AdminController@getForgotpasswordconfirm']);
     
	//Route::get('',['as' => 'dashboard', 'uses' =>'Admin\HomeController@getIndex']);
	Route::get('/dashboard', ['as' => 'dashboard','uses' => 'JoshController@showHome']);

	Route::group(['middleware' => ['sentinel.admin']], function () {
		
		Route::group(['middleware' => ['role.admin']], function () {
			/* for user */
			Route::resource('user','Admin\UserController');
			Route::resource('role','Admin\RoleController');

			/* for city */
			Route::resource('city','Admin\CityController');

			/* for country */
			Route::resource('country','Admin\CountryController');

			/* for township */
			Route::resource('township','Admin\TownshipController');
		});

		/* for delivery */
		Route::get('deliverycompany/editcity/{id}',['as' => 'deliverycompany/editcity', 'uses' =>'Admin\DeliverycompanyController@editCity']);
		Route::post('deliverycompany/editcity/{id}','Admin\DeliverycompanyController@postEditcity');
		Route::post('deletecity/{id}',['as' => 'deletecity', 'uses' =>'Admin\DeliverycompanyController@postDeletecity']);
		Route::resource('deliverycompany','Admin\DeliverycompanyController');
		Route::resource('deliverystaff','Admin\DeliverystaffController');
		Route::resource('deliverytransaction','Admin\DeliverytransactionController');
		Route::resource('deliverystafflocation','Admin\DeliverystafflocationController');
		Route::resource('deliverylocation','Admin\DeliverylocationController');


		/* for Shipper */
		Route::resource('shipping','Admin\ShippingController');
		// Route::resource('shipper','Admin\ShipperController');
		// Route::resource('shippinginformation','Admin\ShippinginformationController');
		Route::resource('shippingtransaction','Admin\ShippingtransactionController');
		Route::post('confirm-shipping/{id}','Admin\ConfirmShippingController@postConfirmshipping')->middleware('throttle:1');

		/*For Shippging list by Shipper*/
		Route::get('shippinglist/{id}',['as' => 'shippinglist', 'uses' =>'Admin\MylistController@getShippinglist']);
		Route::get('notsendinglist/{id}',['as' => 'notsendinglist', 'uses' =>'Admin\MylistController@getNotsendinglist']);
		Route::get('pendinglist/{id}',['as' => 'pendinglist', 'uses' =>'Admin\MylistController@getPendinglist']);

		Route::group(['middleware' => ['role.staff']], function () {
			/*For Receive Order list by Delivery staff*/
			Route::get('neworderlist',['as' => 'neworderlist', 'uses' =>'Admin\MylistController@getNeworderlist']);
			Route::get('receiveorderlist',['as' => 'receiveorderlist', 'uses' =>'Admin\MylistController@getReceiveorderlist']);
			Route::get('acceptorderlist',['as' => 'acceptorderlist', 'uses' =>'Admin\MylistController@getAcceptorderlist']);
			Route::get('completeorderlist',['as' => 'completeorderlist', 'uses' => 'Admin\MylistController@getCompleteorderlist']);
			Route::get('addstaff/{id}',['as' => 'addstaff', 'uses' =>'Admin\MylistController@getAddstaff']);
			Route::post('addstaff/{id}','Admin\MylistController@postAddstaff');
			Route::post('complete/{id}',['as' => 'complete', 'uses' =>'Admin\MylistController@postComplete']);
			Route::post('accept/{id}',['as' => 'accept', 'uses' =>'Admin\MylistController@postAccept']);
			Route::post('cancel/{id}',['as' => 'cancel', 'uses' =>'Admin\MylistController@postCancel']);
			Route::post('receive/{id}',['as' => 'receive', 'uses' =>'Admin\MylistController@postReceive']);
			Route::get('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@getEditdelivery']);
			Route::post('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@postEditdelivery']);
		});
		/* For Parcel */
		Route::resource('parcel','Admin\ParcelController');


	}); 
	
});
 

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class City extends Model
{
	use SoftDeletes;

    protected $dates = ['deleted_at'];
    public function country()
    {
    	return $this->belongsTo('App\Country');
    }

     public function township()
    {
        return $this->hasMany('App\Township');
    }
}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Country;
use App\City;
use Sentinel;
use Illuminate\Http\Response;
use Validator,ErrorException;
use App\Http\Requests\CityCreateRequest;
use App\Http\Controllers\Controller;
 

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
        if ($request->route()->getPrefix() == "/admin") {
            $city= City::with('country')->with('township')->orderBy('name', 'asc')->paginate(10);
             return view('admin.city.index', compact('city'));
        }
        $city= City::with('country')->with('township')->orderBy('name', 'asc')->get();    
         return response()->json($city);
         
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $countries = Country::orderBy('name', 'asc')->get();
        if ($request->route()->getPrefix() == "/admin") {
            return view('admin.city.create',compact('countries',$countries));
        }        
         return response()->json($countries);
         
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $validator = Validator::make($request->all(), [
            'name'              => 'required|unique:cities,name',
            'name_mm'           => 'required',
            'code'              => 'required',
            'country'           => 'required',
             
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            }
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('name_mm'))
                return response()->json($validator->errors()->first('name_mm'), 400);
            if($validator->errors()->has('code'))
                return response()->json($validator->errors()->first('code'), 400);
            if($validator->errors()->has('country'))
                return response()->json($validator->errors()->first('country'), 400);            
        }


        $city = new City;
         
        $city->name       = $request->name;
        $city->name_mm    = $request->name_mm;
        $city->code       = $request->code;
        $city->country_id = $request->country;
        if ($request->enable == true) {
            $city->status = 1;
        }
        else{
            $city->status = 0;
        }
        $city->save();
        if ($request->route()->getPrefix() == "/admin") {
             return redirect()->route('admin.city.index');
        }
        return response()->json($city);
         
 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $city = City::with('country')->find($id);
        $countries = Country::all();   
        if ($request->route()->getPrefix() == "/admin") {
             return view('admin.city.edit', compact('city','countries'));
        }        
        return response()->json($city);
         
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name'              => 'required|unique:cities,name,'.$id,
            'name_mm'           => 'required',
            'code'              => 'required',
            'country'           => 'required',
             
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            }
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('name_mm'))
                return response()->json($validator->errors()->first('name_mm'), 400);
            if($validator->errors()->has('code'))
                return response()->json($validator->errors()->first('code'), 400);
            if($validator->errors()->has('country'))
                return response()->json($validator->errors()->first('country'), 400);            
        }

        $city = City::find($id);
         
        $city->name = $request->name;
        $city->name_mm = $request->name_mm;
        $city->code = $request->code;
        $city->country_id = $request->country;
        if ($request->enable == true) {
            $city->status = 1;
        }
        else{
            $city->status = 0;
        }  
        $city->update();
        if ($request->route()->getPrefix() == "/admin") {
             return redirect()->route('admin.city.index');
        }
        return response()->json($city);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $city = City::find($id);
        $city->delete();
    }
}

resources/views/admin/city/create.blade.php
@extends ('admin.layout.default')
@section('title')
Create City
@stop
@section('content')
<section class="content-header">
    <h1>City</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>City</li>
        <li class="active">Create City</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="archive-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Create City
                    </h4>
                </div>
                <div class="panel-body">
                	<div class="alert-danger">
						 {{ $errors->first('message') }}
					</div>
					<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal" action="{{ route('admin.city.store') }}" method="post">
							 <p>
								<label for="name" class="control-label">City Name</label>
								<input type="text" name="name" class="form-control"/>
								<div class="errors">
									{{ $errors->first('name') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="name_mm" class="control-label">City Myanmar Name</label>
								<input type="text" name="name_mm" class="form-control"/>
								<div class="errors">
									{{ $errors->first('name_mm') }}	
								</div>	 			
							 </p>
							 <p>
								<label for="code" class="control-label">City Code</label>
								<input type="text" name="code" class="form-control"/>
								 <div class="errors">
									{{ $errors->first('code') }}	
								</div>				
							 </p>
							 <p>
								<label for="country" class="control-label">Country</label>								 
								<select class="form-control" name="country">
								   
								   	<?php foreach ($countries as $roles) { ?>
								  		<option value={{ $roles->id }}><?php echo $roles->name ; ?></option>}
								  	<?php } ?>						   
								</select>								 			
							 </p>
							 <p>
							 	<input name="enable" type="checkbox" id="chkquick" value="false"
                                       onchange="if(this.checked) this.value='true'; else this.value='false';">
							 	<label for="enable">Enable</label>
							 </p>
							<button type="submit" class="btn btn-primary">Create</button>
							<a class="btn btn-primary" href="{{ route('admin.city.index') }}">Cancel</a>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</section>    
	 
@stop

resources/views/admin/city/edit.blade.php
@extends ('admin.layout.default')
@section('title')
Edit City
@stop
@section('content')
<section class="content-header">
    <h1>City</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>City</li>
        <li class="active">Edit City</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Edit City
                    </h4>
                </div>
                <div class="panel-body">
                	<div class="alert-danger">
						 {{ $errors->first('message') }}
					</div>
					<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal" action="{{ route('admin.city.update',$city->id ) }}" method="post">
						<input name="_method" type="hidden" value="PUT">
						<?php echo csrf_field(); ?>
							 <p>
								<label for="name" class="control-label">City Name</label>
								<input type="text" name="name" class="form-control" value="{{ $city->name }}" />
								<div class="errors">
									{{ $errors->first('name') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="name_mm" class="control-label">City Myanmar Name</label>
								<input type="text" name="name_mm" class="form-control" value="{{ $city->name_mm }}" />
								<div class="errors">
									{{ $errors->first('name_mm') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="code" class="control-label">City Code</label>
								<input type="text" name="code" class="form-control" value="{{ $city->code }}" />
								 <div class="errors">
									{{ $errors->first('code') }}	
								</div>				
							 </p>
							 <p>
								<label for="country" class="control-label">Country</label>								 
								<select class="form-control" name="country">
								   	<?php foreach ($countries as $roles) { ?>
								  		<option value="{{ $roles->id }}" {{ $roles->name  == $city->country->name ? 'selected' : null }}>{{ $roles->name }}</option>}
								  	<?php } ?>						   
								</select>								 			
							 </p>
							 <p>
							 	<input name="enable" type="checkbox" id="chkquick" {{ $city->status  == 1 ? 'checked' : null }}
                                       onchange="if(this.checked) this.value='true'; else this.value='false';">
							 	<label for="enable">Enable</label>
							 </p>
							<button type="submit" class="btn btn-primary">Update</button>
							<a class="btn btn-primary" href="{{ route('admin.city.index') }}">Cancel</a>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</section>
	 
@stop

resources/views/admin/city/index.blade.php
@extends('admin.layout.default')
@section('title')
City List
@stop
@section('header_styles')
<!--page level css -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.colReorder.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.scroller.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/js/dataTables/dataTables.bootstrap.css') }}" />
<link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css">
<!--end of page level css-->
@stop
@section('content')
<section class="content-header">
    <h1>City</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>City</li>
        <li class="active">City</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left"> <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        City List
                    </h4>
                </div>
                <div class="panel-body">
                <table class="table table-bordered" id="sample_editable_1">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>City Name</th>
                            <th>City Myanmar Name</th>
                            <th>Code</th>
                            <th>Country Name</th>
                            <th>Status</th>
                            <th>Edit\Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($city as $key => $cities)
                        <tr>  
                        <td>{{ $key+1 }}</td>  
                        <td>{{ $cities->name }}</td>
                        <td>{{ $cities->name_mm}}</td>
                        <td>{{ $cities->code }}</td>
                        <td>{{ $cities->country->name}}</td>
                        <td>
                            @if($cities->status == 1)
                                {{"Active"}}
                            @else
                                {{"Inactive"}}
                            @endif
                        </td>
                        <td>
                        <div class="col-xs-1"> 
                            <a href="{{ route('admin.city.edit', $cities->id) }}">
                                <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="edit product"></i>
                            </a>
                        </div>
                        <div class="col-xs-1">                          
                             <a href="javascript:deleteUser('{{ $cities->id }}');">
                                <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete product"></i>
                             </a>
                        </div>                        
                        </td>
                        </tr>
                        @endforeach    
                    </tbody>
                </table>
                {!! $city->render() !!}
                </div>
            
            </div>
        </div>
    </div>
</section>
@stop
@section('footer_scripts')
 <!-- begining of page level js -->
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.tableTools.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.colReorder.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.scroller.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/dataTables/dataTables.bootstrap.js') }}"></script>
<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
<script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>

<script type="text/javascript">
    $(function(){
        var table = $('#sample_editable_1').DataTable({
              "bInfo": false,
              "bPaginate": false,
               
          } );
        
    });

    function deleteUser(id) {
        if (confirm('Are you sure want to delete?')) {
        $.ajax({
            type: "DELETE",
            url: '/admin/city/' + id, //resource
            success: function() {
                    window.location = 'city';
                 
            }
        });
    }
}
</script>

@stop