app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// Route::get('/', function () {
//     return view('welcome');
// });
 

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::get('socket', 'SocketController@index');
// Route::post('sendmessage', 'SocketController@sendMessage');
// Route::get('writemessage', 'SocketController@writemessage');
Route::group(['prefix' => 'admin','middleware' => ['web']], function () {
	 
 
    Route::get('register',['as' => 'register', 'uses' => 'Admin\AdminController@getRegister']);
    Route::post('register','Admin\AdminController@postRegister');
    Route::get('login',['as' => 'login', 'uses' => 'Admin\AdminController@getLogin']);
    Route::post('login','Admin\AdminController@postSignin');
    Route::get('logout',['as' => 'logout', 'uses' => 'Admin\AdminController@getLogout']);

    Route::get('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@getForgotpassword']);
    Route::post('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@postForgotpassword']);

    Route::get('forgot-password-confirm',['as' => 'forgot-password-confirm', 'uses' => 'Admin\AdminController@getForgotpasswordconfirm']);
     
	//Route::get('',['as' => 'dashboard', 'uses' =>'Admin\HomeController@getIndex']);
	Route::get('/dashboard', ['as' => 'dashboard','uses' => 'JoshController@showHome']);

	Route::group(['middleware' => ['sentinel.admin']], function () {
		
		Route::group(['middleware' => ['role.admin']], function () {
			/* for user */
			Route::resource('user','Admin\UserController');
			Route::resource('role','Admin\RoleController');

			/* for city */
			Route::resource('city','Admin\CityController');

			/* for country */
			Route::resource('country','Admin\CountryController');

			/* for township */
			Route::resource('township','Admin\TownshipController');
		});

		/* for delivery */
		Route::get('deliverycompany/editcity/{id}',['as' => 'deliverycompany/editcity', 'uses' =>'Admin\DeliverycompanyController@editCity']);
		Route::post('deliverycompany/editcity/{id}','Admin\DeliverycompanyController@postEditcity');
		Route::post('deletecity/{id}',['as' => 'deletecity', 'uses' =>'Admin\DeliverycompanyController@postDeletecity']);
		Route::resource('deliverycompany','Admin\DeliverycompanyController');
		Route::resource('deliverystaff','Admin\DeliverystaffController');
		Route::resource('deliverytransaction','Admin\DeliverytransactionController');
		Route::resource('deliverystafflocation','Admin\DeliverystafflocationController');
		Route::resource('deliverylocation','Admin\DeliverylocationController');


		/* for Shipper */
		Route::resource('shipping','Admin\ShippingController');
		// Route::resource('shipper','Admin\ShipperController');
		// Route::resource('shippinginformation','Admin\ShippinginformationController');
		Route::resource('shippingtransaction','Admin\ShippingtransactionController');
		Route::post('confirm-shipping/{id}','Admin\ConfirmShippingController@postConfirmshipping')->middleware('throttle:1');

		/*For Shippging list by Shipper*/
		Route::get('shippinglist/{id}',['as' => 'shippinglist', 'uses' =>'Admin\MylistController@getShippinglist']);
		Route::get('notsendinglist/{id}',['as' => 'notsendinglist', 'uses' =>'Admin\MylistController@getNotsendinglist']);
		Route::get('pendinglist/{id}',['as' => 'pendinglist', 'uses' =>'Admin\MylistController@getPendinglist']);

		Route::group(['middleware' => ['role.staff']], function () {
			/*For Receive Order list by Delivery staff*/
			Route::get('neworderlist',['as' => 'neworderlist', 'uses' =>'Admin\MylistController@getNeworderlist']);
			Route::get('receiveorderlist',['as' => 'receiveorderlist', 'uses' =>'Admin\MylistController@getReceiveorderlist']);
			Route::get('acceptorderlist',['as' => 'acceptorderlist', 'uses' =>'Admin\MylistController@getAcceptorderlist']);
			Route::get('completeorderlist',['as' => 'completeorderlist', 'uses' => 'Admin\MylistController@getCompleteorderlist']);
			Route::get('addstaff/{id}',['as' => 'addstaff', 'uses' =>'Admin\MylistController@getAddstaff']);
			Route::post('addstaff/{id}','Admin\MylistController@postAddstaff');
			Route::post('complete/{id}',['as' => 'complete', 'uses' =>'Admin\MylistController@postComplete']);
			Route::post('accept/{id}',['as' => 'accept', 'uses' =>'Admin\MylistController@postAccept']);
			Route::post('cancel/{id}',['as' => 'cancel', 'uses' =>'Admin\MylistController@postCancel']);
			Route::post('receive/{id}',['as' => 'receive', 'uses' =>'Admin\MylistController@postReceive']);
			Route::get('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@getEditdelivery']);
			Route::post('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@postEditdelivery']);
		});
		/* For Parcel */
		Route::resource('parcel','Admin\ParcelController');


	}); 
	
});
 

app/Delivery_staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Delivery_staff extends Model
{
    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function delivery_company()
    {
    	return $this->belongsTo('App\Delivery_company');
    }

    public function delivery_transaction()
    {
    	return $this->hasMany('App\Delivery_transaction');
    }

    public function delivery_staff_location()
    {
        return $this->hasMany('App\Delivery_staff_location');
    }
}

app/Http/Controllers/Admin/DeliverystaffController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Delivery_staff;
use App\Delivery_company;
use App\Http\Requests;
use App\User;
use DB;
use Sentinel;
use Validator,ErrorException;
use App\Http\Controllers\Controller;

class DeliverystaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {       
        if ($user = Sentinel::getUser()){
            if ($user->inRole('deliverycompany')){
                 $staff = Delivery_staff::where('user_id',$user->id)->first();
                 $deliverystaffs = Delivery_staff::with('user')->where('delivery_company_id',$staff->delivery_company_id)->orderBy('created_at', 'desc')->paginate(10);
            }
            else {
                $deliverystaffs = Delivery_staff::with('delivery_company','user')->orderBy('created_at', 'desc')->paginate(10);
            }
        }
            
        if($request->route()->getPrefix() == "/admin") {
             return view('admin.deliverystaff.index', compact('deliverystaffs'));
        }   
        return response()->json($deliverystaffs);
    }

    public function getlist($id)
    {
        $user = Sentinel::findById($id);
        if ($user->inRole('deliverycompany')){
            $staff = Delivery_staff::where('user_id',$user->id)->first();
            $deliverystaffs = Delivery_staff::with('user')->where('delivery_company_id',$staff->delivery_company_id)->orderBy('created_at', 'desc')->get();
        }
        else {
            $deliverystaffs = Delivery_staff::with('delivery_company','user')->orderBy('created_at', 'desc')->get();
        }
        return response()->json($deliverystaffs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        if ($user = Sentinel::getUser()){
            if ($user->inRole('deliverycompany')){
                $staff = Delivery_staff::where('user_id',$user->id)->first();                
                $companies = Delivery_company::find($staff->delivery_company_id);
            }
            else {

                  $companies = Delivery_company::all();
            }
        }
       
        //return response($company);
        return view("admin.deliverystaff.create",compact("companies"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'              => 'required',
            'email'             => 'required|email|unique:users,email',
            'password'          => 'required',
            'phone'             => 'required',
            'company'           => 'required',
                          
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            } 
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('email'))
                return response()->json($validator->errors()->first('email'), 400);
            if($validator->errors()->has('password'))
                return response()->json($validator->errors()->first('password'), 400);
            if($validator->errors()->has('phone'))
                return response()->json($validator->errors()->first('phone'), 400);
            if($validator->errors()->has('company'))
                return response()->json($validator->errors()->first('company'), 400);                   
        }
        $credentials = [   
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => $request->password,
            'phone'     => $request->phone,             
        ];
        DB::beginTransaction();
        try {
            $user = Sentinel::registerAndActivate($credentials,true);
            $role = $request->role ? $request->role : "deliverystaff";
             
                $rolename = Sentinel::findRoleByName($role);
                if($rolename)
                    $rolename->users()->attach($user);  

                $staff = new Delivery_staff;
                $staff->user_id = $user->id;
                $staff->delivery_company_id = $request->company;
                $staff->save();
             

            DB::commit();
            if($request->route()->getPrefix() == "/admin") {
                return redirect()->route('admin.deliverystaff.index');
            }  
            return response()->json("Successful!");
           
            
        } catch (Exception $e) {
            DB::rollBack();
            return response()->json("something wrong!");
        }

         
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Request $request)
    {
        $staff = Delivery_staff::with('delivery_company')->where('id',$id)->first();
        $user = Sentinel::findById($staff->user_id);
        $staff["user"] = $user;
         if($request->route()->getPrefix() == "/admin") {
            return view('admin.deliverystaff.edit',compact("staff"));
        } 
        return response()->json($staff);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name'              => 'required',
            'email'             => 'required|email',
            'phone'             => 'required',
            'company'           => 'required',
                          
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            } 
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('email'))
                return response()->json($validator->errors()->first('email'), 400);
            if($validator->errors()->has('phone'))
                return response()->json($validator->errors()->first('phone'), 400);
            if($validator->errors()->has('company'))
                return response()->json($validator->errors()->first('company'), 400);                   
        }

        $credentials = [   
            'name'      => $request->name,
            'email'     => $request->email,
            'phone'     => $request->phone,
            'company'   => $request->company             
        ];
        DB::beginTransaction();
        try {
            $staff = Delivery_staff::find($id);
            $staff->delivery_company_id = $request->company;
            $staff->update();

            $user = Sentinel::findById($staff->user_id);
            $user->name     = $request->name;
            $user->email    = $request->email;
            if ($request->password) {
                $user->password = $request->password;
            }
            
            $user->phone    = $request->phone;
            $user->update();

            DB::commit();
            if($request->route()->getPrefix() == "/admin") {
                return redirect()->route('admin.deliverystaff.index');
            }  
            return response()->json("Successful!");
           
            
        } catch (Exception $e) {
            DB::rollBack();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,Request $request)
    {
         $staff = Delivery_staff::find($id);
         $staff->delete();
         $user = Sentinel::findById($staff->user_id);
         $user->delete();
         if($request->route()->getPrefix() == "/api") {
            return response()->json("Successful");
        } 
    }
}

resources/views/admin/deliverystaff/create.blade.php
@extends ('admin.layout.default')
@section('title')
Create Delivery Staff
@stop
@section('content')
<section class="content-header">
    <h1>Delivery Staff</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Delivery Staff</li>
        <li class="active">Create Delivery Staff</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Create Delivery Staff
                    </h4>
                </div>
                <div class="panel-body">
	                <div class="alert-danger">
							 {{ $errors->first('message') }}
					</div>
					<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal" action="{{ route('admin.deliverystaff.store') }}" method="post">						 
						 	<p>
								<label for="name" class="control-label">name</label>
								<input type="text" name="name" class="form-control"/>
								<div class="errors">
									{{ $errors->first('name') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="email" class="control-label">Email</label>
								<input type="text" name="email" class="form-control"/>
								<div class="errors">
									{{ $errors->first('email') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="password" class="control-label">Password</label>
								<input type="text" name="password" class="form-control"/>
								 <div class="errors">
									{{ $errors->first('password') }}	
								</div>				
							 </p>
							 <p>
								<label for="phone" class="control-label">Phone</label>
								<input type="text" name="phone" class="form-control"/>
								<div class="errors">
									{{ $errors->first('phone') }}	
								</div> 			
							 </p>
							 <p>
								<label for="company" class="control-label">Company</label>								 
								<select class="form-control" name="company">
								@if($user = Sentinel::getUser())
									@if($user->inRole('deliverycompany'))
									<option value={{ $companies->id }}>{{$companies->name}}</option>
									@else
									<option value="">Select Company</option>
									@foreach($companies as $company)	 
								  		<option value={{ $company->id }}>{{$company->name}}</option>
								   	@endforeach	
									@endif
								@endif	   
								</select>
								<div class="errors">
									{{ $errors->first('company') }}	
								</div> 								 			
							 </p>
							 
							<button type="submit" class="btn btn-primary">Create</button>
							<a class="btn btn-primary" href="{{ route('admin.deliverystaff.index') }}">Cancel</a>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</section>
	 
@stop

resources/views/admin/deliverystaff/edit.blade.php
@extends ('admin.layout.default')
@section('title')
Edit Delivery Staff
@stop
@section('content')
<section class="content-header">
    <h1>Delivery Staff</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Delivery Staff</li>
        <li class="active">Delivery Staff</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Edit Delivery Staff
                    </h4>
                </div>
                <div class="panel-body">
                	<div class="alert-danger">
						 {{ $errors->first('message') }}
					</div>
					<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal" action="{{ route('admin.deliverystaff.update',$staff->id ) }}" method="post">
							<input name="_method" type="hidden" value="PUT">
							<?php echo csrf_field(); ?>
							  <p>
								<label for="name" class="control-label">name</label>
								<input type="text" name="name" class="form-control" value="{{ $staff->user->name }}" />
								<div class="errors">
									{{ $errors->first('name') }}	
								</div>
								 			
							 </p>
							 <p>
								<label for="email" class="control-label">Email</label>
								<input type="text" name="email" class="form-control" value="{{$staff->user->email}}"/>
								<div class="errors">
									{{ $errors->first('email') }}	
								</div>
								 			
							 </p>
							 <p>
							 <p class="text-warning">If you don't want to change password... please leave them empty</p>
								<label for="password" class="control-label">Password</label>
								<input type="text" name="password" class="form-control"/>
								 <div class="errors">
									{{ $errors->first('password') }}	
								</div>				
							 </p>
							 <p>
								<label for="phone" class="control-label">Phone</label>
								<input type="text" name="phone" class="form-control" value="{{$staff->user->phone}}"/>
								<div class="errors">
									{{ $errors->first('phone') }}	
								</div> 			
							 </p>
							 <p>
								<label for="company" class="control-label">Company</label>								 
								<select class="form-control" name="company">
									<option value="{{ $staff->delivery_company->id }}">{{$staff->delivery_company->name}}</option>	
								</select>
								<div class="errors">
									{{ $errors->first('company') }}	
								</div> 								 			
							 </p>
							<button type="submit" class="btn btn-primary">Update</button>
							<a class="btn btn-primary" href="{{ route('admin.deliverystaff.index') }}">Cancel</a>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</section>
	 
@stop

resources/views/admin/deliverystaff/index.blade.php
@extends('admin.layout.default')
@section('title')
Delivery Staff List
@stop
@section('header_styles')
<!--page level css -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.colReorder.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.scroller.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/js/dataTables/dataTables.bootstrap.css') }}" />
<link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css">
<!--end of page level css-->
@stop
@section('content')
<section class="content-header">
    <h1>Delivery Staff</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Delivery Staff</li>
        <li class="active">Delivery Staff</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left"> <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Dlivery Staff List
                    </h4>
                </div>
                <div class="panel-body">
                <table class="table table-bordered" id="sample_editable_1">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Company</th>
                            <th>Edit\Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($deliverystaffs as $key => $deliverystaff)
                        <tr>  
                            <td>{{$key+1}}</td>
                            <td>{{$deliverystaff['user']['name']}}</td>
                            <td>{{$deliverystaff['user']['email']}}</td>
                            <td>{{$deliverystaff['user']['phone']}}</td>
                            <td>
                            @if($deliverystaff->delivery_company == null)
                                {{"No Company"}}
                            @else
                                {{$deliverystaff->delivery_company->name }}
                            @endif
                            </td>
                            <td>
                            <div class="col-xs-1"> 
                             @if(Sentinel::getUser()->id != $deliverystaff['user']['id'])
                                <a href="{{ route('admin.deliverystaff.edit', $deliverystaff->id) }}">
                                    <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="edit product"></i>
                                </a>
                            </div>
                            <div class="col-xs-1">                              
                                <a href="javascript:deleteUser('{{ $deliverystaff->id }}');">
                                    <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete product"></i>
                                </a>
                            </div>  
                            @endif  
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $deliverystaffs->render() !!}
                </div>
            </div>
        </div>
    </div>
</section>	
@stop
@section('footer_scripts')
 <!-- begining of page level js -->
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.tableTools.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.colReorder.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.scroller.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/dataTables/dataTables.bootstrap.js') }}"></script>
<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
<script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>

<script type="text/javascript">
    $(function(){
        var table = $('#sample_editable_1').DataTable({
              "bInfo": false,
              "bPaginate": false,
               
          });       
    });

    function deleteUser(id) {
        if (confirm('Are you sure want to delete?')) {
        $.ajax({
            type: "DELETE",
            url: '/admin/deliverystaff/' + id, //resource
            success: function() {
                    window.location = 'deliverystaff';
                 
            }
        });
    }
}
</script>
@stop