app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// Route::get('/', function () {
//     return view('welcome');
// });
 

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::get('socket', 'SocketController@index');
// Route::post('sendmessage', 'SocketController@sendMessage');
// Route::get('writemessage', 'SocketController@writemessage');
Route::group(['prefix' => 'admin','middleware' => ['web']], function () {
	 
 
    Route::get('register',['as' => 'register', 'uses' => 'Admin\AdminController@getRegister']);
    Route::post('register','Admin\AdminController@postRegister');
    Route::get('login',['as' => 'login', 'uses' => 'Admin\AdminController@getLogin']);
    Route::post('login','Admin\AdminController@postSignin');
    Route::get('logout',['as' => 'logout', 'uses' => 'Admin\AdminController@getLogout']);

    Route::get('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@getForgotpassword']);
    Route::post('forgot-password',['as' => 'forgot-password', 'uses' => 'Admin\AdminController@postForgotpassword']);

    Route::get('forgot-password-confirm',['as' => 'forgot-password-confirm', 'uses' => 'Admin\AdminController@getForgotpasswordconfirm']);
     
	//Route::get('',['as' => 'dashboard', 'uses' =>'Admin\HomeController@getIndex']);
	Route::get('/dashboard', ['as' => 'dashboard','uses' => 'JoshController@showHome']);

	Route::group(['middleware' => ['sentinel.admin']], function () {
		
		Route::group(['middleware' => ['role.admin']], function () {
			/* for user */
			Route::resource('user','Admin\UserController');
			Route::resource('role','Admin\RoleController');

			/* for city */
			Route::resource('city','Admin\CityController');

			/* for country */
			Route::resource('country','Admin\CountryController');

			/* for township */
			Route::resource('township','Admin\TownshipController');
		});

		/* for delivery */
		Route::get('deliverycompany/editcity/{id}',['as' => 'deliverycompany/editcity', 'uses' =>'Admin\DeliverycompanyController@editCity']);
		Route::post('deliverycompany/editcity/{id}','Admin\DeliverycompanyController@postEditcity');
		Route::post('deletecity/{id}',['as' => 'deletecity', 'uses' =>'Admin\DeliverycompanyController@postDeletecity']);
		Route::resource('deliverycompany','Admin\DeliverycompanyController');
		Route::resource('deliverystaff','Admin\DeliverystaffController');
		Route::resource('deliverytransaction','Admin\DeliverytransactionController');
		Route::resource('deliverystafflocation','Admin\DeliverystafflocationController');
		Route::resource('deliverylocation','Admin\DeliverylocationController');


		/* for Shipper */
		Route::resource('shipping','Admin\ShippingController');
		// Route::resource('shipper','Admin\ShipperController');
		// Route::resource('shippinginformation','Admin\ShippinginformationController');
		Route::resource('shippingtransaction','Admin\ShippingtransactionController');
		Route::post('confirm-shipping/{id}','Admin\ConfirmShippingController@postConfirmshipping')->middleware('throttle:1');

		/*For Shippging list by Shipper*/
		Route::get('shippinglist/{id}',['as' => 'shippinglist', 'uses' =>'Admin\MylistController@getShippinglist']);
		Route::get('notsendinglist/{id}',['as' => 'notsendinglist', 'uses' =>'Admin\MylistController@getNotsendinglist']);
		Route::get('pendinglist/{id}',['as' => 'pendinglist', 'uses' =>'Admin\MylistController@getPendinglist']);

		Route::group(['middleware' => ['role.staff']], function () {
			/*For Receive Order list by Delivery staff*/
			Route::get('neworderlist',['as' => 'neworderlist', 'uses' =>'Admin\MylistController@getNeworderlist']);
			Route::get('receiveorderlist',['as' => 'receiveorderlist', 'uses' =>'Admin\MylistController@getReceiveorderlist']);
			Route::get('acceptorderlist',['as' => 'acceptorderlist', 'uses' =>'Admin\MylistController@getAcceptorderlist']);
			Route::get('completeorderlist',['as' => 'completeorderlist', 'uses' => 'Admin\MylistController@getCompleteorderlist']);
			Route::get('addstaff/{id}',['as' => 'addstaff', 'uses' =>'Admin\MylistController@getAddstaff']);
			Route::post('addstaff/{id}','Admin\MylistController@postAddstaff');
			Route::post('complete/{id}',['as' => 'complete', 'uses' =>'Admin\MylistController@postComplete']);
			Route::post('accept/{id}',['as' => 'accept', 'uses' =>'Admin\MylistController@postAccept']);
			Route::post('cancel/{id}',['as' => 'cancel', 'uses' =>'Admin\MylistController@postCancel']);
			Route::post('receive/{id}',['as' => 'receive', 'uses' =>'Admin\MylistController@postReceive']);
			Route::get('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@getEditdelivery']);
			Route::post('editdelivery/{id}',['as' => 'editdelivery', 'uses' =>'Admin\MylistController@postEditdelivery']);
		});
		/* For Parcel */
		Route::resource('parcel','Admin\ParcelController');


	}); 
	
});
 

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
 
class User extends \Cartalyst\Sentinel\Users\EloquentUser
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password','phone','nrc_no','photo','code'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','pivot',
    ];

    protected $loginNames = ['email','phone'];

    public function delivery_staff()
    {
        return $this->hasMany('App\Delivery_staff');
    }
      


     
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;
use Sentinel;
use App\Role;
use App\Shipper;
use App\Delivery_staff;
use App\Delivery_company;
use Validator,ErrorException;
use \Cartalyst\Sentinel\Checkpoints\NotActivatedException;
use \Cartalyst\Sentinel\Checkpoints\ThrottlingException;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = Sentinel::getUserRepository()->with('roles','activations')->orderBy('created_at', 'desc')->paginate(10);
         
         if ($request->route()->getPrefix() == "/admin") {            
             return view('admin.user.index', compact('users'));
        }  
        return response()->json($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Delivery_company::all();
        $roles = Role::all();
        return view('admin.user.create',compact("companies","roles"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'               => 'required|unique:users,name',
            'email'              => 'required|email|max:255|unique:users,email',
            'password'           => 'required|min:6',
            'phone'              => 'required|numeric|min:8',
            'role'               => 'required',
             
             
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            }
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('email'))
                return response()->json($validator->errors()->first('email'), 400);
            if($validator->errors()->has('password'))
                return response()->json($validator->errors()->first('password'), 400);
            if($validator->errors()->has('role'))
                return response()->json($validator->errors()->first('role'), 400);
            if($validator->errors()->has('phone'))
                return response()->json($validator->errors()->first('phone'), 400);
             
                        
        }
        
        
         
        $credentials = [   
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => $request->password,
            'phone'     => $request->phone,
            'photo'     => $request->photo,
             
        ];

        $user = Sentinel::registerAndActivate($credentials,true);
        $role = Sentinel::findRoleById($request->role);
         
        if($role){
            $role->users()->attach($user);  
        }
        if ($role->slug == "deliverystaff" || $role->slug == "deliverycompany") {
            $staff = new Delivery_staff;
            $staff->user_id = $user->id;
            $staff->delivery_company_id = $request->company;
            $staff->save();
        }else{
            $shipper = new Shipper;
            $shipper->user_id = $user->id;
            $shipper->name = $request->name;
            $shipper->save();
        }
        
        return redirect()->route('admin.user.index');
         

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), [
            'name'              => 'required',
            'email'             => 'required|email',
            'old_password'      => 'required',
            'phone'             => 'required',                          
        ]);

        if ($validator->fails()) {
            if ($request->route()->getPrefix() == "/admin") {
                return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            } 
            if($validator->errors()->has('name'))
                return response()->json($validator->errors()->first('name'), 400);
            if($validator->errors()->has('email'))
                return response()->json($validator->errors()->first('email'), 400);
            if($validator->errors()->has('old_password'))
                return response()->json($validator->errors()->first('old-password'), 400); 
            if($validator->errors()->has('phone'))
                return response()->json($validator->errors()->first('phone'), 400);                              
        }
        
        $credentials = [
            'email'     => $request->email,
            'password'  => $request->old_password,
        ];
        if (Sentinel::authenticate($credentials)) {
            $user = Sentinel::findById($id);
             
            Sentinel::update($user, array(
                'name'     => $request->name,
                'password' => $request->new_password ? $request->new_password : $request->old_password,
                'phone'    => $request->phone,
                'photo'    => $request->photo,
            ));
	    $user = User::with('roles')->whereid($user->id)->first();
            $staff = Delivery_staff::where('user_id',$user->id)->first();
            $user['staff']=$staff;

            return response()->json($user);
        }else{
            return response()->json('Sorry! Invalid Email or Password',400);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Sentinel::findById($id);
        $user->delete();
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout.default')
@section('title')
Create User
@stop
@section('header_styles')
<!--page level css -->
<link rel="stylesheet" href="{{ asset('assets/vendors/wizard/jquery-steps/css/wizard.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendors/wizard/jquery-steps/css/jquery.steps.css') }}">
<link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />
<!--end of page level css-->
@stop

@section('content')
<section class="content-header">
    <h1>User</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>User</li>
        <li class="active">Create User</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Create City
                    </h4>
                </div>
                <div class="panel-body">
                	<div class="alert-danger">
						 {{ $errors->first('message') }}
					</div>
					<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal"  action="{{ route('admin.user.store') }}" method="post" enctype="multipart/form-data">
							 <p>
								<label for="name" class="control-label">name</label>
								<input type="text" name="name" class="form-control"/>
								<div class="errors">
									{{ $errors->first('name') }}	
								</div>	 			
							 </p>
							 <p>
								<label for="email" class="control-label">Email</label>
								<input type="text" name="email" class="form-control"/>
								<div class="errors">
									{{ $errors->first('email') }}	
								</div>					 			
							 </p>
							 <p>
								<label for="password" class="control-label">Password</label>
								<input type="text" name="password" class="form-control"/>
								 <div class="errors">
									{{ $errors->first('password') }}	
								</div>				
							 </p>
							 <p>
								<label for="phone" class="control-label">Phone</label>
								<input type="text" name="phone" class="form-control"/>
								<div class="errors">
									{{ $errors->first('phone') }}	
								</div>						 			
							 </p>
							 <p>
								<label for="role" class="control-label">Role</label>								 
								<select class="form-control" name="role">
									<option value="">Select Role</option>
									@foreach($roles as $role)	 
								  		<option value={{ $role->id }}>{{$role->slug}}</option>}
								   	@endforeach		   
								</select>
								<div class="errors">
									{{ $errors->first('role') }}	
								</div> 								 			
							 </p>
							 <p>
								<label for="company" class="control-label">Company</label>								 
								<select class="form-control" name="company">
									<option value="">Select Company</option>
									@foreach($companies as $company)	 
								  		<option value={{ $company->id }}>{{$company->name}}</option>}
								   	@endforeach		   
								</select>
								<div class="errors">
									{{ $errors->first('company') }}	
								</div> 								 			
							 </p>
							<button type="submit" class="btn btn-primary">Create</button>
							<a class="btn btn-primary" href="{{ route('admin.user.index') }}">Cancel</a>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</section> 
@stop
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/wizard/jquery-steps/js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('assets/vendors/wizard/jquery-steps/js/jquery.steps.js') }}"></script>
    <script src="{{ asset('assets/vendors/jasny-bootstrap/js/jasny-bootstrap.js') }}"></script>
    <script src="{{ asset('assets/js/pages/form_wizard.js') }}"></script>
@stop

resources/views/admin/user/index.blade.php
@extends('admin.layout.default')
@section('title')
User List
@stop
@section('header_styles')
<!--page level css -->
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.colReorder.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.scroller.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/js/dataTables/dataTables.bootstrap.css') }}" />
<link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css">
<!--end of page level css-->
@stop
@section('content')
<section class="content-header">
    <h1>User</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{route('dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>User</li>
        <li class="active">User</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left"> <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        User List
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered" id="sample_editable_1">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>User Name</th>
                                <th>Email</th>
                                <th>Phone No</th>
                                <th>Status</th>
                                <th>Create At</th>
                                <th>Edit/Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                             @foreach($users as $key => $user)
                             <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->phone}}</td>
                                <td>
                                    @forelse($user->activations as $activate)
                                        @if($activate->completed == 1)
                                            {{"Activated"}}  
                                        @else
                                            {{"Not Activate"}}
                                        @endif
                                    @empty
                                        {{"Not Activate"}}
                                    @endforelse
                                </td>
                                <td>
                                {{$user->created_at->diffForHumans() }}
                                </td>
                                <td>
                                    <div class="col-xs-1"> 
                                        <a href="{{ route('admin.user.edit', $user->id) }}">
                                            <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="edit "></i>
                                        </a>
                                    </div>
                                    @if(Sentinel::getUser()->id != $user->id)
                                    <div class="col-xs-1">                          
                                         <a href="javascript:deleteUser('{{ $user->id }}');">
                                            <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete"></i>
                                         </a>
                                    </div>   
                                    @endif           
                                </td>
                             </tr>
                             @endforeach
                        </tbody>
                    </table>
                    {!! $users->render() !!}
                </div>
            </div>
        </div>
    </div>
</section>
@stop
@section('footer_scripts')
 <!-- begining of page level js -->
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.tableTools.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.colReorder.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.scroller.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/dataTables/dataTables.bootstrap.js') }}"></script>
<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
<script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>

<script type="text/javascript">
    $(function(){
        var table = $('#sample_editable_1').DataTable({
              "bInfo": false,
              "bPaginate": false,
               
          } );
        
    });
    function deleteUser(id) {
        if (confirm('Are you sure want to delete?')) {
        $.ajax({
            type: "DELETE",
            url: '/admin/user/' + id, //resource
            success: function() {
                    window.location = 'user';
                 
            }
        });
    }
}
</script>
@stop